#!/bin/bash
nasm -f elf32 sseutils32.nasm
nasm -f elf32 regression32.nasm
gcc -m32 -msse -O0 -no-pie sseutils32.o regression32.o regression32c.c -o regression32c -lm
pars="";
for arg; do pars=$pars" "$arg; done;
./regression32c $pars
